#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612367_FinalManagmentProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ManagementProject")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTestDB2(TestDB2 instance);
    partial void UpdateTestDB2(TestDB2 instance);
    partial void DeleteTestDB2(TestDB2 instance);
    partial void Inserttestdb3(testdb3 instance);
    partial void Updatetestdb3(testdb3 instance);
    partial void Deletetestdb3(testdb3 instance);
    partial void InsertCategoryDb(CategoryDb instance);
    partial void UpdateCategoryDb(CategoryDb instance);
    partial void DeleteCategoryDb(CategoryDb instance);
    partial void InsertScore_TypeCustomer(Score_TypeCustomer instance);
    partial void UpdateScore_TypeCustomer(Score_TypeCustomer instance);
    partial void DeleteScore_TypeCustomer(Score_TypeCustomer instance);
    partial void InsertDiscountDb(DiscountDb instance);
    partial void UpdateDiscountDb(DiscountDb instance);
    partial void DeleteDiscountDb(DiscountDb instance);
    partial void InsertCustomerDb(CustomerDb instance);
    partial void UpdateCustomerDb(CustomerDb instance);
    partial void DeleteCustomerDb(CustomerDb instance);
    partial void InsertSize36_Product(Size36_Product instance);
    partial void UpdateSize36_Product(Size36_Product instance);
    partial void DeleteSize36_Product(Size36_Product instance);
    partial void InsertSize37_Product(Size37_Product instance);
    partial void UpdateSize37_Product(Size37_Product instance);
    partial void DeleteSize37_Product(Size37_Product instance);
    partial void InsertSize38_Product(Size38_Product instance);
    partial void UpdateSize38_Product(Size38_Product instance);
    partial void DeleteSize38_Product(Size38_Product instance);
    partial void InsertSize39_Product(Size39_Product instance);
    partial void UpdateSize39_Product(Size39_Product instance);
    partial void DeleteSize39_Product(Size39_Product instance);
    partial void InsertSize40_Product(Size40_Product instance);
    partial void UpdateSize40_Product(Size40_Product instance);
    partial void DeleteSize40_Product(Size40_Product instance);
    partial void InsertSize41_Product(Size41_Product instance);
    partial void UpdateSize41_Product(Size41_Product instance);
    partial void DeleteSize41_Product(Size41_Product instance);
    partial void InsertSize42_Product(Size42_Product instance);
    partial void UpdateSize42_Product(Size42_Product instance);
    partial void DeleteSize42_Product(Size42_Product instance);
    partial void InsertReceipt(Receipt instance);
    partial void UpdateReceipt(Receipt instance);
    partial void DeleteReceipt(Receipt instance);
    partial void InsertDetailReceipt(DetailReceipt instance);
    partial void UpdateDetailReceipt(DetailReceipt instance);
    partial void DeleteDetailReceipt(DetailReceipt instance);
    partial void InsertProductDb(ProductDb instance);
    partial void UpdateProductDb(ProductDb instance);
    partial void DeleteProductDb(ProductDb instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::_1612367_FinalManagmentProject.Properties.Settings.Default.ManagementProjectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TestDB2> TestDB2s
		{
			get
			{
				return this.GetTable<TestDB2>();
			}
		}
		
		public System.Data.Linq.Table<testdb3> testdb3s
		{
			get
			{
				return this.GetTable<testdb3>();
			}
		}
		
		public System.Data.Linq.Table<CategoryDb> CategoryDbs
		{
			get
			{
				return this.GetTable<CategoryDb>();
			}
		}
		
		public System.Data.Linq.Table<Score_TypeCustomer> Score_TypeCustomers
		{
			get
			{
				return this.GetTable<Score_TypeCustomer>();
			}
		}
		
		public System.Data.Linq.Table<DiscountDb> DiscountDbs
		{
			get
			{
				return this.GetTable<DiscountDb>();
			}
		}
		
		public System.Data.Linq.Table<CustomerDb> CustomerDbs
		{
			get
			{
				return this.GetTable<CustomerDb>();
			}
		}
		
		public System.Data.Linq.Table<Size36_Product> Size36_Products
		{
			get
			{
				return this.GetTable<Size36_Product>();
			}
		}
		
		public System.Data.Linq.Table<Size37_Product> Size37_Products
		{
			get
			{
				return this.GetTable<Size37_Product>();
			}
		}
		
		public System.Data.Linq.Table<Size38_Product> Size38_Products
		{
			get
			{
				return this.GetTable<Size38_Product>();
			}
		}
		
		public System.Data.Linq.Table<Size39_Product> Size39_Products
		{
			get
			{
				return this.GetTable<Size39_Product>();
			}
		}
		
		public System.Data.Linq.Table<Size40_Product> Size40_Products
		{
			get
			{
				return this.GetTable<Size40_Product>();
			}
		}
		
		public System.Data.Linq.Table<Size41_Product> Size41_Products
		{
			get
			{
				return this.GetTable<Size41_Product>();
			}
		}
		
		public System.Data.Linq.Table<Size42_Product> Size42_Products
		{
			get
			{
				return this.GetTable<Size42_Product>();
			}
		}
		
		public System.Data.Linq.Table<Receipt> Receipts
		{
			get
			{
				return this.GetTable<Receipt>();
			}
		}
		
		public System.Data.Linq.Table<DetailReceipt> DetailReceipts
		{
			get
			{
				return this.GetTable<DetailReceipt>();
			}
		}
		
		public System.Data.Linq.Table<ProductDb> ProductDbs
		{
			get
			{
				return this.GetTable<ProductDb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestDB2")]
	public partial class TestDB2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public TestDB2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.testdb3")]
	public partial class testdb3 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public testdb3()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CategoryDb")]
	public partial class CategoryDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nameType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameTypeChanging(string value);
    partial void OnnameTypeChanged();
    #endregion
		
		public CategoryDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nameType
		{
			get
			{
				return this._nameType;
			}
			set
			{
				if ((this._nameType != value))
				{
					this.OnnameTypeChanging(value);
					this.SendPropertyChanging();
					this._nameType = value;
					this.SendPropertyChanged("nameType");
					this.OnnameTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Score_TypeCustomer")]
	public partial class Score_TypeCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nameTypeCustomer;
		
		private int _minScore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameTypeCustomerChanging(string value);
    partial void OnnameTypeCustomerChanged();
    partial void OnminScoreChanging(int value);
    partial void OnminScoreChanged();
    #endregion
		
		public Score_TypeCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameTypeCustomer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nameTypeCustomer
		{
			get
			{
				return this._nameTypeCustomer;
			}
			set
			{
				if ((this._nameTypeCustomer != value))
				{
					this.OnnameTypeCustomerChanging(value);
					this.SendPropertyChanging();
					this._nameTypeCustomer = value;
					this.SendPropertyChanged("nameTypeCustomer");
					this.OnnameTypeCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minScore", DbType="Int NOT NULL")]
		public int minScore
		{
			get
			{
				return this._minScore;
			}
			set
			{
				if ((this._minScore != value))
				{
					this.OnminScoreChanging(value);
					this.SendPropertyChanging();
					this._minScore = value;
					this.SendPropertyChanged("minScore");
					this.OnminScoreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiscountDb")]
	public partial class DiscountDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nameDiscount;
		
		private int _idProduct;
		
		private int _idTypeCustomer;
		
		private System.Nullable<int> _statusDiscount;
		
		private System.DateTime _startDate;
		
		private System.DateTime _endDate;
		
		private int _percentageDiscount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameDiscountChanging(string value);
    partial void OnnameDiscountChanged();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnidTypeCustomerChanging(int value);
    partial void OnidTypeCustomerChanged();
    partial void OnstatusDiscountChanging(System.Nullable<int> value);
    partial void OnstatusDiscountChanged();
    partial void OnstartDateChanging(System.DateTime value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(System.DateTime value);
    partial void OnendDateChanged();
    partial void OnpercentageDiscountChanging(int value);
    partial void OnpercentageDiscountChanged();
    #endregion
		
		public DiscountDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameDiscount", DbType="NVarChar(100)")]
		public string nameDiscount
		{
			get
			{
				return this._nameDiscount;
			}
			set
			{
				if ((this._nameDiscount != value))
				{
					this.OnnameDiscountChanging(value);
					this.SendPropertyChanging();
					this._nameDiscount = value;
					this.SendPropertyChanged("nameDiscount");
					this.OnnameDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL")]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTypeCustomer", DbType="Int NOT NULL")]
		public int idTypeCustomer
		{
			get
			{
				return this._idTypeCustomer;
			}
			set
			{
				if ((this._idTypeCustomer != value))
				{
					this.OnidTypeCustomerChanging(value);
					this.SendPropertyChanging();
					this._idTypeCustomer = value;
					this.SendPropertyChanged("idTypeCustomer");
					this.OnidTypeCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusDiscount", DbType="Int")]
		public System.Nullable<int> statusDiscount
		{
			get
			{
				return this._statusDiscount;
			}
			set
			{
				if ((this._statusDiscount != value))
				{
					this.OnstatusDiscountChanging(value);
					this.SendPropertyChanging();
					this._statusDiscount = value;
					this.SendPropertyChanged("statusDiscount");
					this.OnstatusDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="DateTime NOT NULL")]
		public System.DateTime startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this.OnstartDateChanging(value);
					this.SendPropertyChanging();
					this._startDate = value;
					this.SendPropertyChanged("startDate");
					this.OnstartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="Date NOT NULL")]
		public System.DateTime endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				if ((this._endDate != value))
				{
					this.OnendDateChanging(value);
					this.SendPropertyChanging();
					this._endDate = value;
					this.SendPropertyChanged("endDate");
					this.OnendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentageDiscount", DbType="Int NOT NULL")]
		public int percentageDiscount
		{
			get
			{
				return this._percentageDiscount;
			}
			set
			{
				if ((this._percentageDiscount != value))
				{
					this.OnpercentageDiscountChanging(value);
					this.SendPropertyChanging();
					this._percentageDiscount = value;
					this.SendPropertyChanged("percentageDiscount");
					this.OnpercentageDiscountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerDb")]
	public partial class CustomerDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nameCustomer;
		
		private int _score;
		
		private string _phoneNumber;
		
		private int _typeCustomer;
		
		private System.Nullable<System.DateTime> _dateOfBirth;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameCustomerChanging(string value);
    partial void OnnameCustomerChanged();
    partial void OnscoreChanging(int value);
    partial void OnscoreChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OntypeCustomerChanging(int value);
    partial void OntypeCustomerChanged();
    partial void OndateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfBirthChanged();
    #endregion
		
		public CustomerDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameCustomer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nameCustomer
		{
			get
			{
				return this._nameCustomer;
			}
			set
			{
				if ((this._nameCustomer != value))
				{
					this.OnnameCustomerChanging(value);
					this.SendPropertyChanging();
					this._nameCustomer = value;
					this.SendPropertyChanged("nameCustomer");
					this.OnnameCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score", DbType="Int NOT NULL")]
		public int score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this.OnscoreChanging(value);
					this.SendPropertyChanging();
					this._score = value;
					this.SendPropertyChanged("score");
					this.OnscoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="Char(11)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeCustomer", DbType="Int NOT NULL")]
		public int typeCustomer
		{
			get
			{
				return this._typeCustomer;
			}
			set
			{
				if ((this._typeCustomer != value))
				{
					this.OntypeCustomerChanging(value);
					this.SendPropertyChanging();
					this._typeCustomer = value;
					this.SendPropertyChanged("typeCustomer");
					this.OntypeCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfBirth", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				if ((this._dateOfBirth != value))
				{
					this.OndateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._dateOfBirth = value;
					this.SendPropertyChanged("dateOfBirth");
					this.OndateOfBirthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size36_Product")]
	public partial class Size36_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduct;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Size36_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size37_Product")]
	public partial class Size37_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduct;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Size37_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size38_Product")]
	public partial class Size38_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduct;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Size38_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size39_Product")]
	public partial class Size39_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduct;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Size39_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size40_Product")]
	public partial class Size40_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduct;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Size40_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size41_Product")]
	public partial class Size41_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduct;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Size41_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size42_Product")]
	public partial class Size42_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProduct;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Size42_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Receipt")]
	public partial class Receipt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idCustomer;
		
		private System.DateTime _datePay;
		
		private decimal _sumMoney;
		
		private int _sumScore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidCustomerChanging(System.Nullable<int> value);
    partial void OnidCustomerChanged();
    partial void OndatePayChanging(System.DateTime value);
    partial void OndatePayChanged();
    partial void OnsumMoneyChanging(decimal value);
    partial void OnsumMoneyChanged();
    partial void OnsumScoreChanging(int value);
    partial void OnsumScoreChanged();
    #endregion
		
		public Receipt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCustomer", DbType="Int")]
		public System.Nullable<int> idCustomer
		{
			get
			{
				return this._idCustomer;
			}
			set
			{
				if ((this._idCustomer != value))
				{
					this.OnidCustomerChanging(value);
					this.SendPropertyChanging();
					this._idCustomer = value;
					this.SendPropertyChanged("idCustomer");
					this.OnidCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datePay", DbType="DateTime NOT NULL")]
		public System.DateTime datePay
		{
			get
			{
				return this._datePay;
			}
			set
			{
				if ((this._datePay != value))
				{
					this.OndatePayChanging(value);
					this.SendPropertyChanging();
					this._datePay = value;
					this.SendPropertyChanged("datePay");
					this.OndatePayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sumMoney", DbType="Money NOT NULL")]
		public decimal sumMoney
		{
			get
			{
				return this._sumMoney;
			}
			set
			{
				if ((this._sumMoney != value))
				{
					this.OnsumMoneyChanging(value);
					this.SendPropertyChanging();
					this._sumMoney = value;
					this.SendPropertyChanged("sumMoney");
					this.OnsumMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sumScore", DbType="Int NOT NULL")]
		public int sumScore
		{
			get
			{
				return this._sumScore;
			}
			set
			{
				if ((this._sumScore != value))
				{
					this.OnsumScoreChanging(value);
					this.SendPropertyChanging();
					this._sumScore = value;
					this.SendPropertyChanged("sumScore");
					this.OnsumScoreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailReceipt")]
	public partial class DetailReceipt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDetailReceipt;
		
		private int _idReceipt;
		
		private System.Nullable<int> _idCustomer;
		
		private int _idProduct;
		
		private int _idTypeProduct;
		
		private int _quantity;
		
		private decimal _unitPriceSell;
		
		private int _size;
		
		private System.Nullable<int> _idDiscount;
		
		private System.Nullable<int> _persentageDiscount;
		
		private System.Nullable<int> _unitBonusScore;
		
		private System.DateTime _datePay;
		
		private decimal _interest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDetailReceiptChanging(int value);
    partial void OnidDetailReceiptChanged();
    partial void OnidReceiptChanging(int value);
    partial void OnidReceiptChanged();
    partial void OnidCustomerChanging(System.Nullable<int> value);
    partial void OnidCustomerChanged();
    partial void OnidProductChanging(int value);
    partial void OnidProductChanged();
    partial void OnidTypeProductChanging(int value);
    partial void OnidTypeProductChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    partial void OnunitPriceSellChanging(decimal value);
    partial void OnunitPriceSellChanged();
    partial void OnsizeChanging(int value);
    partial void OnsizeChanged();
    partial void OnidDiscountChanging(System.Nullable<int> value);
    partial void OnidDiscountChanged();
    partial void OnpersentageDiscountChanging(System.Nullable<int> value);
    partial void OnpersentageDiscountChanged();
    partial void OnunitBonusScoreChanging(System.Nullable<int> value);
    partial void OnunitBonusScoreChanged();
    partial void OndatePayChanging(System.DateTime value);
    partial void OndatePayChanged();
    partial void OninterestChanging(decimal value);
    partial void OninterestChanged();
    #endregion
		
		public DetailReceipt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetailReceipt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDetailReceipt
		{
			get
			{
				return this._idDetailReceipt;
			}
			set
			{
				if ((this._idDetailReceipt != value))
				{
					this.OnidDetailReceiptChanging(value);
					this.SendPropertyChanging();
					this._idDetailReceipt = value;
					this.SendPropertyChanged("idDetailReceipt");
					this.OnidDetailReceiptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idReceipt", DbType="Int NOT NULL")]
		public int idReceipt
		{
			get
			{
				return this._idReceipt;
			}
			set
			{
				if ((this._idReceipt != value))
				{
					this.OnidReceiptChanging(value);
					this.SendPropertyChanging();
					this._idReceipt = value;
					this.SendPropertyChanged("idReceipt");
					this.OnidReceiptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCustomer", DbType="Int")]
		public System.Nullable<int> idCustomer
		{
			get
			{
				return this._idCustomer;
			}
			set
			{
				if ((this._idCustomer != value))
				{
					this.OnidCustomerChanging(value);
					this.SendPropertyChanging();
					this._idCustomer = value;
					this.SendPropertyChanged("idCustomer");
					this.OnidCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduct", DbType="Int NOT NULL")]
		public int idProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				if ((this._idProduct != value))
				{
					this.OnidProductChanging(value);
					this.SendPropertyChanging();
					this._idProduct = value;
					this.SendPropertyChanged("idProduct");
					this.OnidProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTypeProduct", DbType="Int NOT NULL")]
		public int idTypeProduct
		{
			get
			{
				return this._idTypeProduct;
			}
			set
			{
				if ((this._idTypeProduct != value))
				{
					this.OnidTypeProductChanging(value);
					this.SendPropertyChanging();
					this._idTypeProduct = value;
					this.SendPropertyChanged("idTypeProduct");
					this.OnidTypeProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitPriceSell", DbType="Money NOT NULL")]
		public decimal unitPriceSell
		{
			get
			{
				return this._unitPriceSell;
			}
			set
			{
				if ((this._unitPriceSell != value))
				{
					this.OnunitPriceSellChanging(value);
					this.SendPropertyChanging();
					this._unitPriceSell = value;
					this.SendPropertyChanged("unitPriceSell");
					this.OnunitPriceSellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="Int NOT NULL")]
		public int size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDiscount", DbType="Int")]
		public System.Nullable<int> idDiscount
		{
			get
			{
				return this._idDiscount;
			}
			set
			{
				if ((this._idDiscount != value))
				{
					this.OnidDiscountChanging(value);
					this.SendPropertyChanging();
					this._idDiscount = value;
					this.SendPropertyChanged("idDiscount");
					this.OnidDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persentageDiscount", DbType="Int")]
		public System.Nullable<int> persentageDiscount
		{
			get
			{
				return this._persentageDiscount;
			}
			set
			{
				if ((this._persentageDiscount != value))
				{
					this.OnpersentageDiscountChanging(value);
					this.SendPropertyChanging();
					this._persentageDiscount = value;
					this.SendPropertyChanged("persentageDiscount");
					this.OnpersentageDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitBonusScore", DbType="Int")]
		public System.Nullable<int> unitBonusScore
		{
			get
			{
				return this._unitBonusScore;
			}
			set
			{
				if ((this._unitBonusScore != value))
				{
					this.OnunitBonusScoreChanging(value);
					this.SendPropertyChanging();
					this._unitBonusScore = value;
					this.SendPropertyChanged("unitBonusScore");
					this.OnunitBonusScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datePay", DbType="DateTime NOT NULL")]
		public System.DateTime datePay
		{
			get
			{
				return this._datePay;
			}
			set
			{
				if ((this._datePay != value))
				{
					this.OndatePayChanging(value);
					this.SendPropertyChanging();
					this._datePay = value;
					this.SendPropertyChanged("datePay");
					this.OndatePayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interest", DbType="Money NOT NULL")]
		public decimal interest
		{
			get
			{
				return this._interest;
			}
			set
			{
				if ((this._interest != value))
				{
					this.OninterestChanging(value);
					this.SendPropertyChanging();
					this._interest = value;
					this.SendPropertyChanged("interest");
					this.OninterestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductDb")]
	public partial class ProductDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nameProduct;
		
		private int _category;
		
		private decimal _priceImport;
		
		private decimal _priceSell;
		
		private System.Nullable<int> _bonusScore;
		
		private string _unit;
		
		private int _sumQuantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameProductChanging(string value);
    partial void OnnameProductChanged();
    partial void OncategoryChanging(int value);
    partial void OncategoryChanged();
    partial void OnpriceImportChanging(decimal value);
    partial void OnpriceImportChanged();
    partial void OnpriceSellChanging(decimal value);
    partial void OnpriceSellChanged();
    partial void OnbonusScoreChanging(System.Nullable<int> value);
    partial void OnbonusScoreChanged();
    partial void OnunitChanging(string value);
    partial void OnunitChanged();
    partial void OnsumQuantityChanging(int value);
    partial void OnsumQuantityChanged();
    #endregion
		
		public ProductDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameProduct", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nameProduct
		{
			get
			{
				return this._nameProduct;
			}
			set
			{
				if ((this._nameProduct != value))
				{
					this.OnnameProductChanging(value);
					this.SendPropertyChanging();
					this._nameProduct = value;
					this.SendPropertyChanged("nameProduct");
					this.OnnameProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int NOT NULL")]
		public int category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceImport", DbType="Money NOT NULL")]
		public decimal priceImport
		{
			get
			{
				return this._priceImport;
			}
			set
			{
				if ((this._priceImport != value))
				{
					this.OnpriceImportChanging(value);
					this.SendPropertyChanging();
					this._priceImport = value;
					this.SendPropertyChanged("priceImport");
					this.OnpriceImportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceSell", DbType="Money NOT NULL")]
		public decimal priceSell
		{
			get
			{
				return this._priceSell;
			}
			set
			{
				if ((this._priceSell != value))
				{
					this.OnpriceSellChanging(value);
					this.SendPropertyChanging();
					this._priceSell = value;
					this.SendPropertyChanged("priceSell");
					this.OnpriceSellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bonusScore", DbType="Int")]
		public System.Nullable<int> bonusScore
		{
			get
			{
				return this._bonusScore;
			}
			set
			{
				if ((this._bonusScore != value))
				{
					this.OnbonusScoreChanging(value);
					this.SendPropertyChanging();
					this._bonusScore = value;
					this.SendPropertyChanged("bonusScore");
					this.OnbonusScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="NVarChar(50)")]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this.OnunitChanging(value);
					this.SendPropertyChanging();
					this._unit = value;
					this.SendPropertyChanged("unit");
					this.OnunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sumQuantity", DbType="Int NOT NULL")]
		public int sumQuantity
		{
			get
			{
				return this._sumQuantity;
			}
			set
			{
				if ((this._sumQuantity != value))
				{
					this.OnsumQuantityChanging(value);
					this.SendPropertyChanging();
					this._sumQuantity = value;
					this.SendPropertyChanged("sumQuantity");
					this.OnsumQuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
